### ISSUE TITLE
train_X.npy not generated in any files

### ISSUE THREAD

**Issue by alexanderimanicowenrivers** [chirag126/CoroNet#5]
hey there,

I followed the instructions on https://github.com/lindawangg/COVID-Net to get the dataset, which is now complete. 

But all the https://github.com/lindawangg/COVID-Net/blob/master/create_COVIDx.ipynb notebook does is merge all train and test images into one place --- it doesn't create the train and test np arrays which your code requires to be run. 

Can you please push a script to create these?

Thanks,
Alex

**Comment by chirag-agarwall** [comment]
Hello Alex,

Thank you for reaching out. I wasn't able to share the entire training and testing datasets as they are very large (~11Gb). I have uploaded the respective training and testing numpy files on the drive for your use. Can you share your email address so that I can share the same with you?

Thanks,
Chirag

**Comment by alexanderimanicowenrivers** [comment]
mc_rivers@icloud.com, alternatively if you have the python script used to make the numpy files I would prefer that?

**Comment by chirag-agarwall** [comment]
The python snippet used to create the respective numpy files were based on the txt files shared by the authors in [COVID-NET](https://github.com/lindawangg/COVID-Net/). Given below is the script I used for the same.

```
## CREATING THE TRAIN AND TEST DATASET FOR OUR MODELS
trainfile_path = './train_split_v2.txt'
ff = open(trainfile_path, 'r')
trainfile = ff.readlines()
X_train = []
y_train = []
pred = []
for i in range(len(trainfile)):
    line = trainfile[i].split()
    x = cv2.imread(os.path.join('data', 'train', line[1]))
    x = cv2.resize(x, (224, 224))
    X_train.append(x.astype('float32')/255.0)
    y_train.append(mapping[line[2]])
ff.close()

testfile_path = './test_split_v2.txt'
ff = open(testfile_path, 'r')
testfile = ff.readlines()
X_test = []
y_test = []
pred = []
for i in range(len(testfile)):
    line = testfile[i].split()
    x = cv2.imread(os.path.join('data', 'test', line[1]))
    x = cv2.resize(x, (224, 224))
    X_test.append(x.astype('float32')/255.0)
    y_test.append(mapping[line[2]])
ff.close()
```

Hope that helps and best of luck with your project.

**Comment by alexanderimanicowenrivers** [comment]
Hey, thanks but we are missing the mapping function, what is this sorry?

**Comment by chirag-agarwall** [comment]
The mapping is nothing but a dictionary of the classes:
`mapping = {'normal': 0, 'pneumonia': 1, 'COVID-19': 2}`

Hope that helps.
